import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Providers from "./providers";
import "./globals.css";
import LogoutButton from "@/components/LogoutButton";
import Protected from "@/components/protected";
import UserInfo from "@/components/UserInfo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "flex-end",
            gap: "12px",
            padding: "10px 14px",
            borderBottom: "1px solid #e5e7eb",
          }}
        >
          <a
            href="/"
            style={{
              marginRight: "auto",
              textDecoration: "none",
              color: "inherit",
              fontWeight: 600,
            }}
          >
            App
          </a>
          <UserInfo />
          <LogoutButton />
        </header>
        <Providers>
          <Protected>{children}</Protected>
        </Providers>
      </body>
    </html>
  );
}
