ALTER TABLE users
ADD COLUMN IF NOT EXISTS indexno VARCHAR(50) NULL;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS jobid VARCHAR(50) NULL;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS ects VARCHAR(50) NULL;

ALTER TABLE course_registrations
ADD COLUMN IF NOT EXISTS passed BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE exam_registrations
ADD COLUMN IF NOT EXISTS passed BOOLEAN DEFAULT FALSE NOT NULL;

CREATE TABLE IF NOT EXISTS singleton (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    ects TEXT NOT NULL,
    courses JSONB NOT NULL
);